### PR TITLE
Report errors for unproductive nonterminals (GH issue #1)

### PR DESCRIPTION
**Pull request by kuniss**
Hi @linkrope, tried to solve the issue #1.
First real D programming! :smile: 

I added a new option _--ignore-nonproductive_ to force the code generation even if there are non-productive non-terminals for mimic the behavior we had before. 
Not sure, whether it is better to pass `Arguments` as argument down as `Analyze()` or only the boolean value of the option. Please advice. 

I also renamed the `Warning()` method as now it covers the determination of unreachable non-terminals only.

### CODE REVIEW

**Comment by kuniss** [comment]
@linkrope, do you have an idea, why the build fails?
I just checked, I have it in my local environment too but cannot explain it to me...

**Comment by linkrope** [comment]
> @linkrope, do you have an idea, why the build fails? I just checked, I have it in my local environment too but cannot explain it to me...

The test runner is a separate `main`function, so it's necessary to exclude the module with the real `main` function:

> Excluding main source file src/epsilon/main.d from test.

But your `import epsilon.main : Arguments;` will then result in unresolved references. 

Two options:
1. extract `Arguments` in a different module - I don't like this, because `Arguments` kind of documents the usage of `main`
2. use `Settings` - what's only relevant for `main` stays hidden in the `main` module

BTW:  "ignore-nonproductive" is very specific; there could be (too) many similar options.
What's the purpose of this option: does not make sense to let the compiler fail...

**Comment by kuniss** [comment]
Thanks for the hint. Had already the assumption it is caused by the import.
I guess, I would go with the `Settings` solution. 

> BTW: "ignore-nonproductive" is very specific; there could be (too) many similar options.
> What's the purpose of this option: does not make sense to let the compiler fail...

You mean, we could skip the option at all?
I'm wondering a little bit why it did not cause an error with Modual-2 at Epsilon. I guess, I just would like to repeat the Epsilon behavior from the past with that option.
But there is no way around the D compile problem, right? So we should let the generator just fail in that case, isn't it?

**Comment by linkrope** [comment]
That would be worth an experiment: what happens if you declare all nonterminals productive, even if they are not? If some nonterminals are not productive, no code is generated for them, so that the compiler detects errors afterwards. What if code is generated anyway? (Which must somehow fail at runtime because the nonterminal is just not productive).

I think the option is indeed questionable. With the VS Code Plugin the situation can occur that nonterminals are not (yet) productive. But for the compiler generation, both ways are possible: I abort, because the result makes no sense, or I generate code for non-productive nonterminals, because I warned that you use the compiler at your own risk...

**Comment by kuniss** [comment]
Considering your [comment](https://github.com/linkrope/gamma/issues/1#issuecomment-1272344593) at the issue #1, it would make sense to let the generator fail with an error if the start symbol is not productive. For other non-terminals a warning is sufficient.

This would also work well for the VS code extension as it intended to be permanently in the situation of unfinished specifications as long as work is ongoing.

I will change the PR code for that.

**Comment by kuniss** [comment]
@linkrope, I changed the PR implementation such that the generator fails only if the start symbol is unproductive. For all other unproductive nonterminals a warning is issued as before. 

This works also well with the VS code plugin while having uncompleted specifications. With the warning for an unproductive non-terminal some other additional warnings appear (from the ELL1 parser generator):
```
warn: generated compiler contains corrupt code for non-productive nonterminals
warn: generated compiler contains corrupt code for non-productive nonterminals
```
Unfortunately, the VS code plugin seems to have an issue to list warnings, if only warnings have occurred.

I know, this PR has a branch conflict. It's coming from fact that you deleted the Epsilon main.d.
I guess, I will close this PR and reopen a new one as resolving this conflict with git in VS code is beyond my current capabilities.

If possible, I would very appreciate, if you could take a look on  the commit [5d9ef8c](https://github.com/linkrope/gamma/pull/12/commits/5d9ef8c98d74af92f03cdda66dbd7f515349e0c9). I have adapted dub.json to allow issue tests running separately from example tests. Is that OK, from DUB configuration point of view?

**Comment by kuniss** [comment]
I'm going to close this PR as it has a conflict and is replaced by the more concise and conflict free PR #13.

**Pull request closed without merging**
