### PR TITLE
Marked sub-workflows by a prefix

### PR DESCRIPTION
**Pull request by kuniss**
to distinguish them from main workflows.
Using local action defintions (as discussed offline) is not possible due to the extensive use of matrix strategies which makes most of the sub-workflow code, logic and reason for existence...

What do you think is better as prefix "subworkflow" or just and one or two underlines "__"?

### CODE REVIEW

**Comment by linkrope** [comment]
Sorry! I wanted to give this a try:
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-using-an-action-in-the-same-repository-as-the-workflow

I don't like this:
> You must check out your repository before using the action.

I didn't change to a branch, however, damaged master, and had to fix it there:
I'm now using the prefix "actions-" to resemble the `actions/` directory.

**Comment by kuniss** [comment]
No problem.
What do you think? Should we go with your "actions-" prefix or with mine "subworkflow-" prefix?
I guess, in fact it is a sub-workflow, not an action, what we have. 
But, I would not insist. Not so important at the end...

**Comment by linkrope** [comment]
> What do you think? Should we go with your "actions-" prefix or with mine "subworkflow-" prefix? I guess, in fact it is a sub-workflow, not an action, what we have.

Hm: "subworkflow" is quite long. And even GitHub describes "uses" as:
> Selects an action to run as part of a step in your job. An action is a reusable unit of code.

(It's confusing, however, that GitHiub **Actions** runs **workflows**.)

**Comment by kuniss** [comment]
Let's stay with your "actions-" prefix. It is not that important at the end. 
And your changes are already incorporated and working.
So, I'm going to close this PR.

**Pull request closed without merging**
